# Generated by Django 4.2.17 on 2024-12-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='className',
            field=models.TextField(blank=True, null=True),
        ),
    ]
