# Generated by Django 4.2.17 on 2024-12-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('CreateAt', models.DateTimeField()),
                ('updateAt', models.DateTimeField()),
                ('adresse', models.TextField()),
            ],
        ),
    ]
